# Site settings
title: Brad Bolander
email: bolanderbrad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bradbolander.github.io" # the base hostname & protocol for your site
twitter_username: bbolander19
github_username:  bradbolander

# Build settings
markdown: kramdown
